# Generated by Django 4.0.4 on 2022-05-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='diganosis',
            new_name='diagnosis',
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('female', 'FEMALE'), ('others', 'OTHERS'), ('male', 'MALE')], max_length=50),
        ),
    ]
